// Fingerprint runtime
export const currentFingerprintSegments = {
  "timestamp": "2025-08-17T07:48:19.892Z",
  "releaseFingerprint": "3e0ed4ea6965231d30819f2aa5e9e588",
  "dependenciesList": [
    [
      "vue",
      "^3.5.18"
    ],
    [
      "@types/node",
      "^22.5.4"
    ],
    [
      "@typescript-eslint/eslint-plugin",
      "^8.3.0"
    ],
    [
      "@typescript-eslint/parser",
      "^8.3.0"
    ],
    [
      "@vitejs/plugin-vue",
      "^5.1.2"
    ],
    [
      "@vitest/coverage-v8",
      "^2.1.9"
    ],
    [
      "dompurify",
      "^3.1.6"
    ],
    [
      "eslint",
      "^9.10.0"
    ],
    [
      "eslint-config-prettier",
      "^9.1.0"
    ],
    [
      "eslint-plugin-vue",
      "^9.27.0"
    ],
    [
      "markdownlint-cli",
      "^0.41.0"
    ],
    [
      "prettier",
      "^3.3.3"
    ],
    [
      "jsdom",
      "^24.0.0"
    ],
    [
      "@types/jsdom",
      "^21.1.7"
    ],
    [
      "typescript",
      "^5.5.4"
    ],
    [
      "typescript-eslint",
      "^8.39.1"
    ],
    [
      "vite",
      "^5.4.8"
    ],
    [
      "vitest",
      "^2.0.5"
    ]
  ]
};