name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew
      - name: Build & Test (core + feature)
        run: ./gradlew :core:test :feature:test --no-daemon --stacktrace
      - name: Lint (ktlint)
        run: ./gradlew ktlintCheck --no-daemon
      - name: Coverage Reports
        run: ./gradlew :core:jacocoTestReport :feature:jacocoTestReport --no-daemon
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: core/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,feature/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          flags: core,feature
          fail_ci_if_error: true
          verbose: true
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            core/build/reports/tests
            feature/build/reports/tests
      - name: Upload Coverage Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: coverage-reports
            path: |
              core/build/reports/jacoco/jacocoTestReport
              feature/build/reports/jacoco/jacocoTestReport
  auto-format:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew
      - name: Run ktlintFormat
        run: ./gradlew ktlintFormat --no-daemon
      - name: Commit formatting changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "sallie-bot"
            git config user.email "sallie-bot@example.com"
            git add .
            git commit -m "chore: apply ktlint formatting"
            git push || true
          fi
